# Text splitter Configuration
TEXT_SPLITTER_CHUNK_SIZE=2500
TEXT_SPLITTER_CHUNK_OVERLAP=0

# OpenAI Configuration (LM-Studio)
OPEN_AI_API_KEY="lm-studio"
OPEN_AI_BASE_URL="http://127.0.0.1:1234/v1/"

# Hyperparameters
LLM_TEMPERATURE = 0.25
VECTORSTORE_CONFIDENCE_THRESHOLD = 0.5
VECTORSTORE_DOCUMENT_LIMIT = 5